### ISSUE TITLE
Doesn't load on LG G2x

### ISSUE THREAD

**Issue by brentil** [bvalosek/cpuspy#1]
The application fails to load completely with the LG G2x device.

2.2 Stock & 2.3 Stock result in FC on app start.

2.2 Root & 2.3 Root begin to load but result in a black screen that never loads.

**Comment by bvalosek** [comment]
See this post: http://forum.xda-developers.com/showpost.php?p=20087033&postcount=134

**Comment by brentil** [comment]
It now loads but I get the red bar as mentioned.  I am running CM 7.1 now and not the stock OS any longer with the stock CM 7.1 kernel.

Doing find /sys -name "time_in_state" does not return any results so I navigated down to "/sys/devices/system/cpu/cpu0/cpufreq" but there is no stats file or folder.  I also have a "/sys/devices/system/cpu/cpufreq" folder but is empty.

$ cd /sys/devices/system/cpu/cpu0/cpufreq
$ ls -l
-r--r--r--    1 root     root          4096 Dec  7 20:06 affected_cpus
-r--------    1 root     root          4096 Dec  7 20:06 cpuinfo_cur_freq
-r--r--r--    1 root     root          4096 Dec  7 20:06 cpuinfo_max_freq
-r--r--r--    1 root     root          4096 Dec  7 20:06 cpuinfo_min_freq
-r--r--r--    1 root     root          4096 Dec  7 20:06 cpuinfo_transition_latency
-r--r--r--    1 root     root          4096 Dec  7 20:06 related_cpus
-r--r--r--    1 root     root          4096 Dec  7 20:06 scaling_available_governors
-r--r--r--    1 root     root          4096 Dec  7 20:06 scaling_driver
-rw-rw-r--    1 root     system        4096 Dec  6 18:08 scaling_governor
-rw-rw-r--    1 root     system        4096 Dec  6 18:08 scaling_max_freq
-rw-rw-r--    1 root     system        4096 Dec  6 18:08 scaling_min_freq
-rw-r--r--    1 root     root          4096 Dec  7 20:06 scaling_setspeed
$

**Comment by bvalosek** [comment]
It seems the time_in_state file is not exposed from the kernel you are
running. As of right now, I'm not sure there are any other methods of
getting the freq state histogram other than via sysfs. Unless there is
another way I'm unaware of, this needs to be implemented in the CM kernel
you're running, so I'm closing this for now, will re-open if the kernel dev
working on your device has any other ideas.

On Wed, Dec 7, 2011 at 7:12 PM, brentil <
reply@reply.github.com
